spring:
  application:
    name: config
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mathanparamasivan/central-config-repo
          cloneOnStart: true  # Clone the repo when the server starts
          searchPaths: '{application},/{application}-{profile}'  # Search for configuration files specific to the app name
          default-label: main  # Default branch (if using Git)
server:
  port: 8888
